name: tvlist

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
# 解决方案
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04@20240422.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        #run: pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1
        run: pip install selenium requests futures eventlet

      - name: Run itv_all
        run: python ${{ github.workspace }}/tvtest.py
      
      - name: 提交更改
        run: |
          git config --local user.email ${{ secrets.GIT_MAIL }}
          git config --local user.name "two2025"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f

      # 新增的 Gitee 推送步骤
      - name: 配置 Gitee SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITEE_SSH_KEY }}

      - name: 添加 Gitee 远程仓库
        run: |
          git remote add gitee git@gitee.com:${{ secrets.GITEE_USER }}/tv.git  # 替换为您的地址
          git fetch gitee

      - name: 推送到 Gitee
        run: |
          git push gitee HEAD:main --force  # 推送当前分支到 Gitee 的 main 分支
